# Generated by Django 3.2.15 on 2022-09-29 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PainelAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(blank=True, max_length=255)),
                ('name', models.TextField(blank=True, max_length=255)),
                ('session', models.TextField(blank=True, max_length=255)),
                ('channel_name', models.TextField(blank=True, max_length=255)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('painel_votacao', models.URLField(max_length=255)),
                ('pauta_sessao', models.URLField(max_length=255)),
            ],
        ),
    ]
