# Generated by Django 3.2.15 on 2022-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_ativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelativo',
            name='presidente',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='painelativo',
            name='situacao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
